@extends('layouts.admin')

@section('page-title', 'More Initiatives')

@section('content')
<div class="admin-page-head"><div><h2 class="admin-page-title">More Initiatives</h2><p class="admin-page-subtitle">Manage additional community program cards</p></div><a href="{{ route('admin.our-work-initiatives.create') }}" class="btn-primary"><i class="fas fa-plus"></i> Add Initiative</a></div>
<div class="stats-grid"><div class="stat-card"><p class="stat-label">Total Initiatives</p><p class="stat-value">{{ $ourWorkInitiatives->count() }}</p></div><div class="stat-card"><p class="stat-label">Active</p><p class="stat-value">{{ $ourWorkInitiatives->where('status', 1)->count() }}</p></div><div class="stat-card"><p class="stat-label">Inactive</p><p class="stat-value">{{ $ourWorkInitiatives->where('status', 0)->count() }}</p></div><div class="stat-card"><p class="stat-label">Added Today</p><p class="stat-value">{{ $ourWorkInitiatives->where('created_at', '>=', now()->startOfDay())->count() }}</p></div></div>
<div class="page-card"><div class="page-card-header"><p class="page-card-title">All Initiatives</p><span class="page-card-note"><i class="fas fa-info-circle"></i> Select rows to use table actions</span></div><div class="page-card-table"><table class="min-w-full datatable datatable-OurWorkInitiative"><thead><tr><th style="width:40px;"></th><th>ID</th><th>Initiative</th><th>Sort</th><th>Status</th><th style="text-align:right;">Actions</th></tr></thead><tbody>@foreach($ourWorkInitiatives as $initiative)<tr data-entry-id="{{ $initiative->id }}"><td></td><td><span class="id-text">#{{ $initiative->id }}</span></td><td><div class="inline-flex-center"><div class="avatar-circle"><i class="{{ $initiative->icon ?: 'fas fa-plus-circle' }}"></i></div><div><p class="table-main-text">{{ $initiative->title }}</p><p class="table-sub-text">{{ Str::limit($initiative->description, 70) }}</p></div></div></td><td><span class="id-text">{{ $initiative->sort_order ?? 0 }}</span></td><td>@if($initiative->status)<div class="d-flex align-items-center gap-2"><span class="status-dot status-success"></span><span style="font-size:12.5px;color:#374151;">Active</span></div>@else<div class="d-flex align-items-center gap-2"><span class="status-dot status-warning"></span><span style="font-size:12.5px;color:#92400E;">Inactive</span></div>@endif</td><td><div class="action-row"><a href="{{ route('admin.our-work-initiatives.show', $initiative->id) }}" class="btn-outline"><i class="fas fa-eye"></i> View</a><a href="{{ route('admin.our-work-initiatives.edit', $initiative->id) }}" class="btn-outline btn-outline-edit"><i class="fas fa-pencil-alt"></i> Edit</a><form action="{{ route('admin.our-work-initiatives.destroy', $initiative->id) }}" method="POST" style="display:inline;" onsubmit="return confirm('{{ trans('global.areYouSure') }}')">@method('DELETE')@csrf<button type="submit" class="btn-outline btn-outline-danger"><i class="fas fa-trash-alt"></i> Delete</button></form></div></td></tr>@endforeach</tbody></table></div></div>
@endsection
@section('scripts')
@parent
<script>$(function(){initAdminDataTable('.datatable-OurWorkInitiative',{searchPlaceholder:'Search initiatives...',infoText:'Showing _START_-_END_ of _TOTAL_ initiatives'});});</script>
@endsection
