@extends('layouts.admin')

@section('page-title', 'Campaign Page')

@section('content')
<div class="admin-page-head"><div><h2 class="admin-page-title">Campaign Page</h2><p class="admin-page-subtitle">Manage frontend Campaigns page content</p></div><a href="{{ route('admin.campaign-pages.create') }}" class="btn-primary"><i class="fas fa-plus"></i> Add Campaign Content</a></div>
<div class="stats-grid"><div class="stat-card"><p class="stat-label">Total Records</p><p class="stat-value">{{ $campaignPages->count() }}</p></div><div class="stat-card"><p class="stat-label">Active</p><p class="stat-value">{{ $campaignPages->where('status', 1)->count() }}</p></div><div class="stat-card"><p class="stat-label">Inactive</p><p class="stat-value">{{ $campaignPages->where('status', 0)->count() }}</p></div><div class="stat-card"><p class="stat-label">Added Today</p><p class="stat-value">{{ $campaignPages->where('created_at', '>=', now()->startOfDay())->count() }}</p></div></div>
<div class="page-card"><div class="page-card-header"><p class="page-card-title">Campaign Content</p><span class="page-card-note"><i class="fas fa-info-circle"></i> Only active record will show on frontend</span></div><div class="page-card-table"><table class="min-w-full datatable datatable-CampaignPage"><thead><tr><th style="width:40px;"></th><th>ID</th><th>Hero</th><th>Events Title</th><th>CTA Title</th><th>Status</th><th style="text-align:right;">Actions</th></tr></thead><tbody>@foreach($campaignPages as $campaignPage)<tr data-entry-id="{{ $campaignPage->id }}"><td></td><td><span class="id-text">#{{ $campaignPage->id }}</span></td><td><div class="inline-flex-center"><div class="avatar-circle"><i class="fas fa-calendar-alt"></i></div><div><p class="table-main-text">{{ $campaignPage->hero_title ?? '-' }}</p><p class="table-sub-text">{{ Str::limit($campaignPage->hero_badge, 45) }}</p></div></div></td><td style="color:#475569;">{{ $campaignPage->events_title ?? '-' }}</td><td style="color:#475569;">{{ $campaignPage->cta_title ?? '-' }}</td><td>@if($campaignPage->status)<div class="d-flex align-items-center gap-2"><span class="status-dot status-success"></span><span style="font-size:12.5px;color:#374151;">Active</span></div>@else<div class="d-flex align-items-center gap-2"><span class="status-dot status-warning"></span><span style="font-size:12.5px;color:#92400E;">Inactive</span></div>@endif</td><td><div class="action-row"><a href="{{ route('admin.campaign-pages.show', $campaignPage->id) }}" class="btn-outline"><i class="fas fa-eye"></i> View</a><a href="{{ route('admin.campaign-pages.edit', $campaignPage->id) }}" class="btn-outline btn-outline-edit"><i class="fas fa-pencil-alt"></i> Edit</a><form action="{{ route('admin.campaign-pages.destroy', $campaignPage->id) }}" method="POST" style="display:inline;" onsubmit="return confirm('{{ trans('global.areYouSure') }}')">@method('DELETE')@csrf<button type="submit" class="btn-outline btn-outline-danger"><i class="fas fa-trash-alt"></i> Delete</button></form></div></td></tr>@endforeach</tbody></table></div></div>
@endsection
@section('scripts')
@parent
<script>$(function(){initAdminDataTable('.datatable-CampaignPage',{searchPlaceholder:'Search campaign content...',infoText:'Showing _START_-_END_ of _TOTAL_ records'});});</script>
@endsection
