@extends('layouts.admin')

@section('page-title', 'Program Details')

@section('content')
<div class="admin-page-head"><div><h2 class="admin-page-title">Program Details</h2><p class="admin-page-subtitle">Manage detailed Our Work program sections</p></div><a href="{{ route('admin.our-work-details.create') }}" class="btn-primary"><i class="fas fa-plus"></i> Add Detail</a></div>
<div class="stats-grid"><div class="stat-card"><p class="stat-label">Total Details</p><p class="stat-value">{{ $ourWorkDetails->count() }}</p></div><div class="stat-card"><p class="stat-label">Active</p><p class="stat-value">{{ $ourWorkDetails->where('status', 1)->count() }}</p></div><div class="stat-card"><p class="stat-label">Inactive</p><p class="stat-value">{{ $ourWorkDetails->where('status', 0)->count() }}</p></div><div class="stat-card"><p class="stat-label">Reversed</p><p class="stat-value">{{ $ourWorkDetails->where('is_reverse', 1)->count() }}</p></div></div>
<div class="page-card"><div class="page-card-header"><p class="page-card-title">All Program Details</p><span class="page-card-note"><i class="fas fa-info-circle"></i> Select rows to use table actions</span></div><div class="page-card-table"><table class="min-w-full datatable datatable-OurWorkDetail"><thead><tr><th style="width:40px;"></th><th>ID</th><th>Program</th><th>Section ID</th><th>Sort</th><th>Status</th><th style="text-align:right;">Actions</th></tr></thead><tbody>@foreach($ourWorkDetails as $detail)<tr data-entry-id="{{ $detail->id }}"><td></td><td><span class="id-text">#{{ $detail->id }}</span></td><td><div class="inline-flex-center"><div class="avatar-circle"><i class="fas fa-list-check"></i></div><div><p class="table-main-text">{{ $detail->title }}</p><p class="table-sub-text">{{ Str::limit($detail->description, 70) }}</p></div></div></td><td><span class="code-pill">{{ $detail->section_id ?? '-' }}</span></td><td><span class="id-text">{{ $detail->sort_order ?? 0 }}</span></td><td>@if($detail->status)<div class="d-flex align-items-center gap-2"><span class="status-dot status-success"></span><span style="font-size:12.5px;color:#374151;">Active</span></div>@else<div class="d-flex align-items-center gap-2"><span class="status-dot status-warning"></span><span style="font-size:12.5px;color:#92400E;">Inactive</span></div>@endif</td><td><div class="action-row"><a href="{{ route('admin.our-work-details.show', $detail->id) }}" class="btn-outline"><i class="fas fa-eye"></i> View</a><a href="{{ route('admin.our-work-details.edit', $detail->id) }}" class="btn-outline btn-outline-edit"><i class="fas fa-pencil-alt"></i> Edit</a><form action="{{ route('admin.our-work-details.destroy', $detail->id) }}" method="POST" style="display:inline;" onsubmit="return confirm('{{ trans('global.areYouSure') }}')">@method('DELETE')@csrf<button type="submit" class="btn-outline btn-outline-danger"><i class="fas fa-trash-alt"></i> Delete</button></form></div></td></tr>@endforeach</tbody></table></div></div>
@endsection
@section('scripts')
@parent
<script>$(function(){initAdminDataTable('.datatable-OurWorkDetail',{searchPlaceholder:'Search details...',infoText:'Showing _START_-_END_ of _TOTAL_ details'});});</script>
@endsection
