@extends('layouts.admin')

@section('page-title', 'Campaign Events')

@section('content')
<div class="admin-page-head"><div><h2 class="admin-page-title">Campaign Events</h2><p class="admin-page-subtitle">Manage past and upcoming campaign cards</p></div><a href="{{ route('admin.campaign-events.create') }}" class="btn-primary"><i class="fas fa-plus"></i> Add Event</a></div>
<div class="stats-grid"><div class="stat-card"><p class="stat-label">Total Events</p><p class="stat-value">{{ $campaignEvents->count() }}</p></div><div class="stat-card"><p class="stat-label">Active</p><p class="stat-value">{{ $campaignEvents->where('status', 1)->count() }}</p></div><div class="stat-card"><p class="stat-label">Upcoming</p><p class="stat-value">{{ $campaignEvents->where('status_class', 'upcoming')->count() }}</p></div><div class="stat-card"><p class="stat-label">Past</p><p class="stat-value">{{ $campaignEvents->where('status_class', 'past')->count() }}</p></div></div>
<div class="page-card"><div class="page-card-header"><p class="page-card-title">All Campaign Events</p><span class="page-card-note"><i class="fas fa-info-circle"></i> Select rows to use table actions</span></div><div class="page-card-table"><table class="min-w-full datatable datatable-CampaignEvent"><thead><tr><th style="width:40px;"></th><th>ID</th><th>Event</th><th>Date</th><th>Category</th><th>Status</th><th style="text-align:right;">Actions</th></tr></thead><tbody>@foreach($campaignEvents as $event)<tr data-entry-id="{{ $event->id }}"><td></td><td><span class="id-text">#{{ $event->id }}</span></td><td><div class="inline-flex-center"><div class="avatar-circle"><i class="fas fa-calendar-check"></i></div><div><p class="table-main-text">{{ $event->title }}</p><p class="table-sub-text">{{ Str::limit($event->description, 70) }}</p></div></div></td><td style="color:#475569;">{{ $event->event_date ?? '-' }}</td><td><span class="code-pill">{{ $event->category ?? '-' }}</span></td><td>@if($event->status)<div class="d-flex align-items-center gap-2"><span class="status-dot status-success"></span><span style="font-size:12.5px;color:#374151;">Active</span></div>@else<div class="d-flex align-items-center gap-2"><span class="status-dot status-warning"></span><span style="font-size:12.5px;color:#92400E;">Inactive</span></div>@endif</td><td><div class="action-row"><a href="{{ route('admin.campaign-events.show', $event->id) }}" class="btn-outline"><i class="fas fa-eye"></i> View</a><a href="{{ route('admin.campaign-events.edit', $event->id) }}" class="btn-outline btn-outline-edit"><i class="fas fa-pencil-alt"></i> Edit</a><form action="{{ route('admin.campaign-events.destroy', $event->id) }}" method="POST" style="display:inline;" onsubmit="return confirm('{{ trans('global.areYouSure') }}')">@method('DELETE')@csrf<button type="submit" class="btn-outline btn-outline-danger"><i class="fas fa-trash-alt"></i> Delete</button></form></div></td></tr>@endforeach</tbody></table></div></div>
@endsection
@section('scripts')
@parent
<script>$(function(){initAdminDataTable('.datatable-CampaignEvent',{searchPlaceholder:'Search campaign events...',infoText:'Showing _START_-_END_ of _TOTAL_ events'});});</script>
@endsection
