@extends('layouts.admin')

@section('page-title', 'Add Featured Campaign')

@section('content')
<div class="admin-page-head"><div><a href="{{ route('admin.campaign-featureds.index') }}" class="admin-back-link">&larr; Back To List</a><h2 class="admin-page-title">Add Featured Campaign</h2><p class="admin-page-subtitle">Create featured Campaigns page section</p></div></div>
<form method="POST" action="{{ route('admin.campaign-featureds.store') }}" enctype="multipart/form-data">
    @csrf
    <div class="admin-form-grid"><div class="form-card"><div class="form-card-header"><div class="form-card-icon"><i class="fas fa-star"></i></div><div><p class="form-card-title">Featured Information</p><p class="form-card-subtitle">Add featured campaign details</p></div></div><div class="form-card-body">
        @foreach([['status_label','Status Label','Upcoming'],['badge','Badge','Featured Campaign'],['title','Title','Free Health Camp for Local Communities'],['event_date','Event Date','12 June 2026'],['location','Location','Community Center'],['audience','Audience','Open for All'],['primary_button_text','Primary Button Text','View Details'],['primary_button_link','Primary Button Link','/campaigns'],['secondary_button_text','Secondary Button Text','Join Campaign'],['secondary_button_link','Secondary Button Link','/volunteer']] as $field)<div class="field-group"><label class="field-label" for="{{ $field[0] }}">{{ $field[1] }} @if($field[0] === 'title')<span class="req">*</span>@endif</label><div class="input-icon-wrap"><i class="fas fa-pen icon"></i><input type="text" name="{{ $field[0] }}" id="{{ $field[0] }}" value="{{ old($field[0], $field[2]) }}" class="field-input {{ $errors->has($field[0]) ? 'error' : '' }}" {{ $field[0] === 'title' ? 'required' : '' }}></div>@if($errors->has($field[0]))<p class="field-error"><i class="fas fa-exclamation-circle"></i> {{ $errors->first($field[0]) }}</p>@endif</div>@endforeach
        <div class="field-group"><label class="field-label" for="description">Description</label><textarea name="description" id="description" rows="4" class="field-input">{{ old('description') }}</textarea></div>
        <div class="field-group"><label class="field-label" for="image">Image</label><div class="input-icon-wrap"><i class="fas fa-image icon"></i><input type="file" name="image" id="image" class="field-input"></div></div>
    </div></div><div class="form-card"><div class="form-card-header"><div class="form-card-icon"><i class="fas fa-cog"></i></div><div><p class="form-card-title">Settings</p><p class="form-card-subtitle">Sorting and visibility</p></div></div><div class="form-card-body"><div class="field-group"><label class="field-label" for="sort_order">Sort Order</label><div class="input-icon-wrap"><i class="fas fa-sort-numeric-down icon"></i><input type="number" name="sort_order" id="sort_order" value="{{ old('sort_order', 0) }}" class="field-input"></div></div><div class="field-group"><label class="field-label" for="status">Status</label><div class="input-icon-wrap"><i class="fas fa-toggle-on icon"></i><select name="status" id="status" class="field-input"><option value="1" {{ old('status', 1) == 1 ? 'selected' : '' }}>Active</option><option value="0" {{ old('status', 1) == 0 ? 'selected' : '' }}>Inactive</option></select></div></div></div></div></div>
    <div class="form-actions"><button type="submit" class="btn-primary"><i class="fas fa-save"></i> Save Featured</button><a href="{{ route('admin.campaign-featureds.index') }}" class="btn-ghost">{{ trans('global.cancel') }}</a></div>
</form>
@endsection
