@extends('layouts.admin')

@section('page-title', 'Featured Campaigns')

@section('content')
<div class="admin-page-head"><div><h2 class="admin-page-title">Featured Campaigns</h2><p class="admin-page-subtitle">Manage featured Campaigns page section</p></div><a href="{{ route('admin.campaign-featureds.create') }}" class="btn-primary"><i class="fas fa-plus"></i> Add Featured</a></div>
<div class="stats-grid"><div class="stat-card"><p class="stat-label">Total Featured</p><p class="stat-value">{{ $campaignFeatureds->count() }}</p></div><div class="stat-card"><p class="stat-label">Active</p><p class="stat-value">{{ $campaignFeatureds->where('status', 1)->count() }}</p></div><div class="stat-card"><p class="stat-label">Inactive</p><p class="stat-value">{{ $campaignFeatureds->where('status', 0)->count() }}</p></div><div class="stat-card"><p class="stat-label">Added Today</p><p class="stat-value">{{ $campaignFeatureds->where('created_at', '>=', now()->startOfDay())->count() }}</p></div></div>
<div class="page-card"><div class="page-card-header"><p class="page-card-title">All Featured Campaigns</p><span class="page-card-note"><i class="fas fa-info-circle"></i> First active record will show on frontend</span></div><div class="page-card-table"><table class="min-w-full datatable datatable-CampaignFeatured"><thead><tr><th style="width:40px;"></th><th>ID</th><th>Campaign</th><th>Date</th><th>Sort</th><th>Status</th><th style="text-align:right;">Actions</th></tr></thead><tbody>@foreach($campaignFeatureds as $featured)<tr data-entry-id="{{ $featured->id }}"><td></td><td><span class="id-text">#{{ $featured->id }}</span></td><td><div class="inline-flex-center"><div class="avatar-circle"><i class="fas fa-star"></i></div><div><p class="table-main-text">{{ $featured->title }}</p><p class="table-sub-text">{{ Str::limit($featured->description, 70) }}</p></div></div></td><td style="color:#475569;">{{ $featured->event_date ?? '-' }}</td><td><span class="id-text">{{ $featured->sort_order ?? 0 }}</span></td><td>@if($featured->status)<div class="d-flex align-items-center gap-2"><span class="status-dot status-success"></span><span style="font-size:12.5px;color:#374151;">Active</span></div>@else<div class="d-flex align-items-center gap-2"><span class="status-dot status-warning"></span><span style="font-size:12.5px;color:#92400E;">Inactive</span></div>@endif</td><td><div class="action-row"><a href="{{ route('admin.campaign-featureds.show', $featured->id) }}" class="btn-outline"><i class="fas fa-eye"></i> View</a><a href="{{ route('admin.campaign-featureds.edit', $featured->id) }}" class="btn-outline btn-outline-edit"><i class="fas fa-pencil-alt"></i> Edit</a><form action="{{ route('admin.campaign-featureds.destroy', $featured->id) }}" method="POST" style="display:inline;" onsubmit="return confirm('{{ trans('global.areYouSure') }}')">@method('DELETE')@csrf<button type="submit" class="btn-outline btn-outline-danger"><i class="fas fa-trash-alt"></i> Delete</button></form></div></td></tr>@endforeach</tbody></table></div></div>
@endsection
@section('scripts')
@parent
<script>$(function(){initAdminDataTable('.datatable-CampaignFeatured',{searchPlaceholder:'Search featured campaigns...',infoText:'Showing _START_-_END_ of _TOTAL_ featured'});});</script>
@endsection
