@extends('layouts.admin')
@section('page-title', 'Edit Gallery Page')
@section('content')
<div class="admin-page-head"><div><a href="{{ route('admin.gallery-pages.index') }}" class="admin-back-link">&larr; Back To List</a><h2 class="admin-page-title">Edit Gallery Page</h2><p class="admin-page-subtitle">Update frontend Gallery page content</p></div></div>
<form method="POST" action="{{ route('admin.gallery-pages.update',$galleryPage->id) }}">@method('PUT')@csrf
@php $sections=[
'Hero Section'=>[['hero_badge','Hero Badge','text','fas fa-certificate'],['hero_title','Hero Title','text','fas fa-heading'],['hero_description','Hero Description','textarea','fas fa-align-left'],['hero_primary_button_text','Primary Button Text','text','fas fa-mouse-pointer'],['hero_primary_button_link','Primary Button Link','text','fas fa-link'],['hero_secondary_button_text','Secondary Button Text','text','fas fa-mouse-pointer'],['hero_secondary_button_link','Secondary Button Link','text','fas fa-link'],['hero_feature_icon','Feature Icon','text','fas fa-icons'],['hero_feature_title','Feature Title','text','fas fa-heading'],['hero_feature_text','Feature Text','textarea','fas fa-align-left'],['hero_image_one','Hero Image One Path','text','fas fa-image'],['hero_image_two','Hero Image Two Path','text','fas fa-image'],['hero_image_three','Hero Image Three Path','text','fas fa-image'],['hero_image_four','Hero Image Four Path','text','fas fa-image']],
'Photo Gallery'=>[['photos_badge','Photos Badge','text','fas fa-certificate'],['photos_title','Photos Title','text','fas fa-heading'],['photos_description','Photos Description','textarea','fas fa-align-left'],['filter_one','Filter One','text','fas fa-filter'],['filter_two','Filter Two','text','fas fa-filter'],['filter_three','Filter Three','text','fas fa-filter'],['filter_four','Filter Four','text','fas fa-filter'],['filter_five','Filter Five','text','fas fa-filter'],['filter_six','Filter Six','text','fas fa-filter']],
'Albums & Videos'=>[['albums_badge','Albums Badge','text','fas fa-certificate'],['albums_title','Albums Title','text','fas fa-heading'],['albums_description','Albums Description','textarea','fas fa-align-left'],['videos_badge','Videos Badge','text','fas fa-certificate'],['videos_title','Videos Title','text','fas fa-heading'],['videos_description','Videos Description','textarea','fas fa-align-left'],['videos_button_text','Videos Button Text','text','fas fa-mouse-pointer'],['videos_button_link','Videos Button Link','text','fas fa-link']],
'CTA Section'=>[['cta_badge','CTA Badge','text','fas fa-certificate'],['cta_title','CTA Title','text','fas fa-heading'],['cta_description','CTA Description','textarea','fas fa-align-left'],['cta_primary_button_text','Primary Button Text','text','fas fa-mouse-pointer'],['cta_primary_button_link','Primary Button Link','text','fas fa-link'],['cta_secondary_button_text','Secondary Button Text','text','fas fa-mouse-pointer'],['cta_secondary_button_link','Secondary Button Link','text','fas fa-link']],
]; @endphp
<div class="admin-form-grid">@foreach($sections as $sectionTitle=>$fields)<div class="form-card"><div class="form-card-header"><div class="form-card-icon"><i class="fas fa-layer-group"></i></div><div><p class="form-card-title">{{ $sectionTitle }}</p><p class="form-card-subtitle">Manage {{ strtolower($sectionTitle) }} content</p></div></div><div class="form-card-body"><div class="row">@foreach($fields as $field)@php [$name,$label,$type,$icon]=$field; $value=old($name,$galleryPage->$name??''); $isTextarea=$type==='textarea'; $col=$isTextarea?'col-md-12':'col-md-6'; @endphp<div class="{{ $col }}"><div class="field-group"><label class="field-label" for="{{ $name }}">{{ $label }}</label>@if($isTextarea)<textarea name="{{ $name }}" id="{{ $name }}" rows="4" class="field-input">{{ $value }}</textarea>@else<div class="input-icon-wrap"><i class="{{ $icon }} icon"></i><input type="{{ $type }}" name="{{ $name }}" id="{{ $name }}" value="{{ $value }}" class="field-input"></div>@endif</div></div>@endforeach</div></div></div>@endforeach<div class="form-card"><div class="form-card-header"><div class="form-card-icon"><i class="fas fa-toggle-on"></i></div><div><p class="form-card-title">Status Settings</p><p class="form-card-subtitle">Control frontend visibility</p></div></div><div class="form-card-body"><div class="field-group"><label class="field-label" for="status">Status <span class="req">*</span></label><div class="input-icon-wrap"><i class="fas fa-toggle-on icon"></i><select name="status" id="status" class="field-input"><option value="1" {{ old('status',$galleryPage->status??1)==1?'selected':'' }}>Active</option><option value="0" {{ old('status',$galleryPage->status??1)==0?'selected':'' }}>Inactive</option></select></div></div></div></div></div>
<div class="form-actions"><button class="btn-primary"><i class="fas fa-save"></i> Update Gallery Page</button><a href="{{ route('admin.gallery-pages.index') }}" class="btn-ghost">{{ trans('global.cancel') }}</a></div></form>
@endsection
